# Generated by Django 4.1.7 on 2023-04-02 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consulta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='horaDeChegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
